# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9160029c72b035fb716eb332a1f1dd5109e5cea0a11e0550acc6df929781a5ecae8a8f8e8912589ad991c7018589b21b126eefff55ed8a7a9994619fb328f87

test:
  secret_key_base: 1cff10cac1fdf546f826ae675f95c78b3a382d84586fde1030b6a77c7afc1552e506344877d4925e18a556a5d89ff89aba039d1da75c8a314bd4ad357cd98733

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
